name: Workflow ReactJs App
on:
  push:
    branches:
      - 'master'
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v3
      - name: Install Nodejs for runner
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      - name: Install dependencies
        run: npm ci
      - name: Running Tests
        run: npm test